language: node_js
node_js:
  - 6
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run lint
  - npm run build
  - npm test
after_success:
  - test $TRAVIS_BRANCH = "master" && sh ./buildDockerImage.sh
